name: GitHub Project Connect Action
description: Connect Pull Request statuses to Issues on GitHub Project boards.
author: "@wktk"
inputs:
  github-token:
    description: "GitHub API token with repo scope.  GITHUB_TOKEN cannot be used as it doesn't have access to the Projects API."
    required: true
  column-url:
    description: 'URL of the column to move cards.'
  project-id:
    description: 'Numeric ID of the target GitHub Project'
  column-id:
    description: 'Numeric ID of the destination column'
  to-column:
    description: 'Deprecated.  Please use column-id instead.'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: credit-card
  color: blue
